AppBundle\Entity\Address:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AddressRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        street:
            type: string
            length: 255
        zip:
            type: string
            length: 255
        city:
            type: string
            length: 255
        country:
            type: string
            length: 255
        phonenumber:
            type: string
            length: 255
        birthday:
            type: string
            length: 255
        email:
            type: string
            length: 255
        picture:
            type: string
            length: 255
    lifecycleCallbacks: {  }
